language: python
python:
  - "2.7"

install:
  - pushd
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
  - popd

script:
  - ./scripts/build-doc.sh

before_deploy:
  - rm .gitignore

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch:
      shex-lite-2.0-dev
