language: python
python:
  - "2.7"

install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update

script:
  - ./scripts/build-doc.sh

before_deploy:
  - rm .gitignore

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
